language: ruby
cache: bundler
rvm:
  - 2.1.2
addons:
  postgresql: 9.6
  # firefox: "42.0"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cups cups-pdf cups-bsd libcups2-dev
  - sudo apt-get install -qq -y imagemagick libmagickwand-dev nodejs
  - "curl \"https://gist.githubusercontent.com/telbiyski/ec56a92d7114b8631c906c18064ce620/raw/a5429f4aedf16bfb8cf56b593517d7f0b33136cf/install%2520phantomjs%25202.1.1%2520-%2520ubuntu\" | bash"
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  # - 'export DISPLAY=:99.0'
  - 'cp config/app_config.example.yml config/app_config.yml'
  - 'cp config/secrets.example.yml config/secrets.yml'
  - 'psql -c "create database print_hub_test;" -U postgres'
  - 'psql -c "create database abaco_test;" -U postgres'
  - 'bundle exec rake db:migrate'
