language: ruby
cache: bundler
rvm:
  - 2.1.2
addons:
  postgresql: 9.6
  # firefox: "42.0"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cups cups-pdf cups-bsd libcups2-dev
  - sudo apt-get install -qq -y imagemagick libmagickwand-dev nodejs build-essential chrpath libssl-dev libxft-dev
  - sudo apt-get install -qq -y libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev -y
  - export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
  - wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/$PHANTOM_JS.tar.bz2
  - sudo tar xvjf $PHANTOM_JS.tar.bz2
  - sudo mv $PHANTOM_JS /usr/local/share
  - sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin/phantomjs
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  # - 'export DISPLAY=:99.0'
  - 'cp config/app_config.example.yml config/app_config.yml'
  - 'cp config/secrets.example.yml config/secrets.yml'
  - 'psql -c "create database print_hub_test;" -U postgres'
  - 'psql -c "create database abaco_test;" -U postgres'
  - 'bundle exec rake db:migrate'
