language: ruby
dist: bionic
cache: bundler
rvm:
  - 2.6.6
  - 2.7.1
git:
  depth: 1
addons:
  postgresql: 12
  apt:
    packages:
      - libcups2-dev
      - cups
      - cups-bsd
      - cups-pdf
      - libmagickwand-dev
      - imagemagick
      - nodejs
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
services:
  - postgresql
stages:
  - build
  - test
before_script:
  - 'cp config/app_config.example.yml config/app_config.yml'
  - 'cp config/secrets.example.yml config/secrets.yml'
  - 'psql -c "create database abaco_test;" -U postgres'
  - 'bundle exec rails db:create db:migrate'
install:
  - 'rm ${BUNDLE_GEMFILE}.lock'
  - 'eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-$PWD/vendor/bundle}'
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main

jobs:
  include:
    - stage: build
      script: docker build -t abaco .
      install: skip
      before_script:
        - 'cp config/app_config.example.yml config/app_config.yml'
        - 'cp config/secrets.example.yml config/secrets.yml'
      env:
      rvm:
      addons:
        apt:
          packages:
            - docker-ce
      services:
        - docker
