# Email config
smtp:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: 'username@change.me'
  password: '<password>'
  authentication: 'plain'
  enable_starttls_auto: true

# Public host for customer mailer
public_host: 'public.domain.com'

# Local IP for domains
local_server_ip: '192.168.0.7'

# Printers that show only for admin, Pipe separated (without spaces)
private_printers: 'printer_1|printer_2'

# Name of the subdomains
subdomains:
  users: 'prints'
  customers: 'fotocopia'

# Mailgun Api key to validate emails
mailgun_api_key: 'pubkey-11111111111111111111111111111111'
