defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: print_hub
  password: print_hub

development:
  <<: *defaults
  database: print_hub_development

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'print_hub' %>
  password: <%= ENV['TRAVIS'] ? '' : 'print_hub' %>
  database: print_hub_test

production:
  <<: *defaults
  database: print_hub_production

staging:
  <<: *defaults
  database: print_hub_staging

