defaults: &defaults
  # Rails secret  token `rake secret`
  secret_key_base: 'b36b157a9d227002305cb35d6da2e87855be91ae12c338cb508a30f4cf15dfc91d3c5a48f44e45e75ffb5fa8069cac7ef3c297518aa75a1af048b9e8bb0c5efc'
  # Mailgun Api key to validate emails
  mailgun_api_key: 'pubkey-somekey'
  # Bugsnag
  bugsnag_api_key: 'apikey'
  # gdrive details https://developers.google.com/drive/web/auth/web-server
  gdrive:
    cert: <%= Rails.root.join('certs', 'gdrive.p12') %>
    secret: notasecret
    issuer: 'longid@developer.gserviceaccount.com'
    roles:
      owner: [owner@gmail.com]
      writer: [writer@gmail.com, writer2@gmail.com]


development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
