defaults: &defaults
  secret_key_base: '68be9b049740623bcf4c1f9ef2907aa51910c7ad35e2a634cb9aa2d44994131020f5152ad8827e69ef443f1d441b3ba8d3f58070a782b423c5137cf422cfb57b'
  gdrive:
    cert: <%= Rails.root.join('certs', 'gdrive.p12') %>
    secret: notasecret
    issuer: '219445140861-e5v7lqbnljtu1dthf0iluvnv60m7d1lg@developer.gserviceaccount.com'
    roles:
      owner: [nestorcoppi@gmail.com]
      writer: [cetem.utn.mendoza@gmail.com, nestor.coppi@gmail.com]


development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
