defaults: &defaults
  secret_key_base: 'rake secret'
  # Mailgun Api key to validate emails
  mailgun_api_key: 'pubkey-somekey'
  # Bugsnag
  bugsnag_api_key: 'apikey'
  # gdrive details https://developers.google.com/drive/web/auth/web-server
  gdrive:
    cert: <%= Rails.root.join('certs', 'gdrive.p12') %>
    secret: notasecret
    issuer: 'longid@developer.gserviceaccount.com'
    roles:
      owner: [owner@gmail.com]
      writer: [writer@gmail.com, writer2@gmail.com]


development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
